### ISSUE TITLE
Mirror to an external server that require a ssh key

### ISSUE THREAD

**Issue by weirdfoo** [ef-labs/stash-hook-mirror#18]
I'm trying to mirror my changes to another server that I can only connect using public key authentication. The problem is that I can't find how to specify my key and the remote ssh server connection always fail.  I tried setting the key in the stash user's .ssh folder without success.  Any Idea ?

The error I get is :

Failed in pushing to mirror: An error occurred while executing an external process: '/usr/bin/git push server' exited with code 128 saying: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by oviliz** [comment]
Where is the Wiki? Can't find any on how to start with this... :(
