### ISSUE TITLE
Feature: Mirror to CodeCommit. 

### ISSUE THREAD

**Issue by brettswift** [ef-labs/stash-hook-mirror#41]
Mirroring to CodeCommit on AWS would be nice.  It's a bit more complicated and would require some configuration, however I think it would be doable.

An alternative but less desireable method would be to zip the repo up and ship it to S3,  more specifically a URL - like API Gateway.   However with repos that get a lot of use it might be best to stick with CodeCommit.

**Comment by adrianluisgonzalez** [comment]
What changes would be required for CodeCommit?  

It looks like it supports https and ssh with granular IAM control:
http://docs.aws.amazon.com/codecommit/latest/userguide/getting-started.html#getting-started-permissions

**Comment by bram1028** [comment]
I just did this myself. You have to use an IAM user. Create or edit an existing IAM user and at the bottom of the "Security credentials" tab, there's a section called "HTTPS Git credentials for AWS CodeCommit" to generate a username/password for HTTPS access. You can also use SSH by uploading a public key and then it generates an "SSH key ID" which you use as the username.

You'll have to attach a policy that grants access to the repo ARN. See the IAM docs for that.

See http://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-without-cli.html for more information.
