### ISSUE TITLE
Mirror only specific branches

### ISSUE THREAD

**Issue by christiangalsterer** [ef-labs/stash-hook-mirror#53]
Hi,

we have some use cases where we want to mirror only a few branches, e.g. based on a branch pattern and not overwrite remote branches. I think your add-on would be a good baseline for this but would requires some additional features. 

Would you in general interest in this feature (could potentially also help in #48) and if so would you be open for a contribution via a PR?

Thanks in advance
Christian

**Comment by christiangalsterer** [comment]
I had some time and have already an implementation available. I will submit a PR tomorrow.

There is one open question. When the user specifies a branches pattern and saves the configuration the correct implementation still mirrors everything and not only the branches which matches the pattern.

Shall we keep this or shall we also change it in a way that it only mirrors the branches with matches the branch pattern? This would require an additional git command call to get all available branches.

**Comment by christiangalsterer** [comment]
Just submitted PR #54 for your review. Please let me know of any comments, changes, etc.

**Comment by adrianluisgonzalez** [comment]
Thanks for the contribution, this is definitely something I have thought about and see value to adding.  The code looks good, just missing some unit test coverage for your changes.

**Comment by christiangalsterer** [comment]
Thanks for the fast reply. Will add some unit tests tomorrow.

**Comment by christiangalsterer** [comment]
Unit tests are added, please let me know in case of questions.

**Comment by adrianluisgonzalez** [comment]
Sorry, will try to look at this and merge tomorrow.

**Comment by christiangalsterer** [comment]
np

**Comment by adrianluisgonzalez** [comment]
@christiangalsterer I was just running the mirror plugin after merge and I noticed everything is still mirrored when first set up:

```
        // if an empty list of RefChanges was provided we assume this was caused by triggering after a config change.
        // same if no branch pattern was specified we sync all branches
        if(refChanges.isEmpty() || settings.branchesIncludePattern.isEmpty()) {
            builder.argument("+refs/heads/*:refs/heads/*");
        } else {
            .....
```

Rather than using regular expressions, would it be easier to just specify the refspecs to mirror?  That would ensure only the appropriate branches are ever mirrored.  For example, if I only want to mirror `master` and `feature/*` branches I could have the following: 
```
+refs/heads/master:refs/heads/master
+refs/heads/feature/*:refs/heads/feature/*
```

Thoughts?

See this feature branch: https://github.com/ef-labs/stash-hook-mirror/tree/feature/mirror-ref-spec

**Comment by christiangalsterer** [comment]
Hi,

thanks for merging the PR. W.r.t your first question, this is also where I was not sure about how to deal with it, see my second comment in this issue. 
W.r.t. regex vs. refspec, I was also thinking about this and based on my experience, I see regex in add-ons more often than refspecs, therefore I went for regex. But refspec is also fine and feature branch looks ok for me.

**Comment by adrianluisgonzalez** [comment]
Thanks for being understanding.  

I see a few benefits to supporting refspec such as it allows you to do mapping to different namespaces on the remote mirror.  Additionally you can control mirroring tags, pull requests, notes, etc.

**Comment by christiangalsterer** [comment]
sure makes sense. Do you already have an idea when you can provide a next release?

**Comment by christiangalsterer** [comment]
Please ignore my last comment, just saw that you already the releases.
