### ISSUE TITLE
Issue with mirroring with SSH

### ISSUE THREAD

**Issue by christiangalsterer** [ef-labs/stash-hook-mirror#56]
Hi @adrianluisgonzalez,

I have an issue with mirroring using SSH. In the documentation it is mentioned "If using ssh, ensure your private key is installed for the user stash runs under". WHat is meant with "your" in this case. A "technical users" for the Bitbucket instance which needs to be created or the private key of the users which makes some changes leading a mirror action. I guess/assume the first one but wanted to double-check before trigging some internal IT requests.

**Comment by adrianluisgonzalez** [comment]
Correct, it should be an SSH key for the OS user that bitbucket server runs as.  I agree it is a bit confusing.  Feel free to suggest clearer text.

**Comment by christiangalsterer** [comment]
Ok, thanks for the clarification and now it is working. Maybe the documentation can be updated with an example to make it more clear.
