### ISSUE TITLE
Error "the receiving end does not support --atomic push" when using with AWS CodeCommit

### ISSUE THREAD

**Issue by derdeka** [ef-labs/stash-hook-mirror#57]
After upgrade from v2.1.0 to v2.3.0 the sync with aws codecommit is broken - i got the following message in bitbutcket error logs:

`com.atlassian.bitbucket.scm.CommandFailedException: '/usr/bin/git push --prune --atomic ssh://codecommit-eu-central-1/v1/repos/test --force +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/*' exited with code 128 saying: fatal: the receiving end does not support --atomic push`

It seems that codecommit does not support atomic commits. Is ist possible to make "Atomic commit" as an option/checkbox?

**Comment by stweise** [comment]
Having the same issue. +1

**Comment by adrianluisgonzalez** [comment]
Released v2.3.1
