### ISSUE TITLE
How to do massive url edit?

### ISSUE THREAD

**Issue by lGuillaume124** [ef-labs/stash-hook-mirror#61]
Hello,

I'm using the hook on hundreds of repositories on my Bitbucket instance. They all mirror to the same destination. Unfortunately I have to change the mirror URL and I'm trying to find a way to edit all of the configurations at the same time. Is it possible ?

**Comment by adrianluisgonzalez** [comment]
Yes, but you'll need to do it at a database level.  The repository hook settings are stored using the `com.atlassian.bitbucket.setting.Settings` object.  

The following SQL commands should find the relevant settings in the `sta_shared_lob` table:
```
select l.* 
  from sta_repo_hook h 
  join sta_shared_lob l 
    on h.lob_id = l.id 
  where h.hook_key = 'com.englishtown.stash-hook-mirror:mirror-repository-hook';
```

Hope this helps

**Comment by lGuillaume124** [comment]
Awesome! Thank you very much!
