### ISSUE TITLE
Incompatible with BitBucket 6.0.1

### ISSUE THREAD

**Issue by rinkeb** [ef-labs/stash-hook-mirror#69]
Hi,

Getting this after updating to BitBucket 6.0.1: 
**"This app is not compatible with your Bitbucket instance."**

Any chance this could be fixed? Thanx!

**Comment by petermcd** [comment]
Hey @rinkeb in the event you have not seen a new version has been committed by the maintainer which resolves the issue. You should be able to update using the GUI.

**Comment by adrianluisgonzalez** [comment]
Thanks for the reports. Version 3.0.0 adds support for Bitbucket 6.x.

**Comment by rinkeb** [comment]
thanx, appreciated!
