### ISSUE TITLE
Support for using personal access tokens to authentication to remote BBS instances

### ISSUE THREAD

**Issue by jqassar** [ef-labs/stash-hook-mirror#72]
Hello,

Up to this point, we have been successfully using SSH connections to set up BBS->BBS push mirroring of certain repositories.  We are now entering into a new use case, where we don't have the access necessary to set up the key configuration in a straightforward manner.   Using username/password would solve our immediate problem, but is vulnerable to policy changes around password rotation.

Atlassian has somewhat recently added personal access tokens as a way of granting repository/API access without requiring transmission of passwords in the calls.  This would be a very convenient way of managing mirror access without having to crack open the hosting OS and installing keys.

Is there any way to supply PATs as an alternate to using username (for git) or u/p (for https)?

**Comment by adrianluisgonzalez** [comment]
I haven't tried this, but it looks like you should be able to use the PAT with the plugin as is:
https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html

> For git operations, you can use your personal access token as a substitute for your password.

Can you try using basic auth with a username and the PAT for the password?

**Comment by jqassar** [comment]
You're absolutely correct.  Reading further into the configuration made it clear it could drop in for the password, so this is no longer valid.  Now we just need to figure out how to configure the plugin programmatically.
