### ISSUE TITLE
No 2FA support for github

### ISSUE THREAD

**Issue by EugenMayer** [ef-labs/stash-hook-mirror#78]
Trying to mirror to github, but it does not work ( i cannot see any log entries or anything else ).

I wild guess it is because of 2FA?

**Comment by adrianluisgonzalez** [comment]
Can you use ssh keys?

**Comment by EugenMayer** [comment]
since i use a containerized bitbucket server, adding keys on the cli to the shell user is nothing that i can do just like that - short answer is, not i cannot

**Comment by viceice** [comment]
@EugenMayer you need to create a `Personal access token` with repo scope and use as password

https://github.com/settings/tokens
