### ISSUE TITLE
Bitbucket 7.x Support

### ISSUE THREAD

**Issue by mahaag** [ef-labs/stash-hook-mirror#81]
We are using this plugin and just updated our Bitbucket Server to 7.x. Unfortunately the plugin now doesn't work anymore:

![bitbucket-mirror](https://user-images.githubusercontent.com/33893932/77671817-69d4a380-6f88-11ea-90c3-343e2aae5319.png)

Is there an update of this plugin upcoming in the next time?

**Comment by mnightingale** [comment]
I just ignored it and hit enable and it seems to work.

**Comment by TheKrizz** [comment]
Are there any plans for an official Bitbucket 7.x Support?

**Comment by kms254** [comment]
An update to officially support 7.x would be nice. Has anyone had it not work?

**Comment by DenisBY** [comment]
It works out of the box. Just enable it. If you use it with AWS CodeCommit you need to un-check 'Atomic'.

**Comment by adrianluisgonzalez** [comment]
Published a new 3.2.0 version with 7.x support.
